branch-defaults:
  default:
    environment: Udagrambackend-env
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: ahmad-udagram
  branch: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  profile: default
  repository: null
  sc: git
  workspace_type: Application
